openapi: 3.0.3
info:
  title: Ezra e-commerce
  version: '1.0.0'
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Validates credentials with server and returns the user object.
      description: >-
        Login or login attempt email is sent. Checks for login attempts in the past 24 hours and locks account if too many attempts were made.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: me@email.com
              password: supersafe123!
      responses:
        '200':
          description: >-
            credentials are valid, responds with user object. resets failed login attempts. Updates last login at. and clears the password reset timestamps.
        '400':
          description: >-
            error reason is too many failed attempts in 24 hrs, the account is locked try again later.
        '401':
          description: >-
            credentials are invalid, error code 3 reason wrong password. Increases the attempts count and adds a timestamp to the attempts timestamp log.
        '404':
          description: >-
            credentials are invalid, error code 4 reason account does not exists.
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logs the user out.
      description: >-
        This updates the last loged at timestamp. This is a post because we want
        to fail on further calls with already loged out or other errors.
      responses:
        '200':
          description: logged out succesfully!
        '400':
          description: user has already logged out / session has expired. these edge cases wont update last logout timestamp.
          content:
            application/json:
              examples:
                already logged out:
                  value: |-
                    {
                        "code":1,
                        "reason":"user has already logged out"
                    }
                user tried to logout but session was expired:
                  value: |-
                    {
                        "code": 2,
                        "reason": "user attempted to log out after the session expired (last login was over 72 hours ago)"
                    }
  /auth/forgot:
    post:
      tags:
        - Authentication
      summary: Starts the password recovery flow.
      description: Checks for limit of recovery attempts then continues with flow accordingly .
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: my_email_from_2nd_grade@mail.com
      responses:
        '200':
          description: >-
            Increases the count of attempts, adds a timestamp. Sets the reset token. Adds an email to the email queue with a link with the attempt token.
        '400':
          description: >-
            error reason is too many attempts in 24 hours, reset is blocked, try again later.
        '404':
          description: account does not exist
  /auth/reset:
    post:
      tags:
        - Authentication
      summary: Submits a new password for a user
      description: >-
        Checks if the reset password token provided is valid, checks if password fulfills parameters (length min/max). If all is good, hashes and updates password.
      requestBody:
        required: true
        content:
          application/json:
            example:
              reset_token: TE3fEU8S80rg1EelA3jmEetVokFvLgTK
              password: definitelywontforget!213
              repeat_password: definitelywontforget!213
      responses:
        '200':
          description: reset successfull. Goes to login screen, does not auto login.
        '404':
          description: the reset token is not valid
        '400':
          description: >-
            reset passwords do not match (validations error) / the token has expired! (latest timestamp is over 24hours)

  /users:
    post:
      tags:
        - Authentication
      summary: Signs up a new user.
      description: Creates a new user in db, with default role of client. A sys admin has to perform an account role update to upgrade the account to manager.
      requestBody:
        required: true
        content:
          application/json:
            example:
              first_name: Johns
              last_name: Smiths
              email: johns.smiths@email.com
              password: password123$
              repeat_password: password123$
      responses:
        '201':
          description: sign up successful.  Sends Welcome email. Then performs login logic. Includes user object in response.
        '409':
          description: error code 5, reason is a user with the given email already exists.
        '400':
          description: >-
            VALIDATION ERROR, reason is the user email is invalid OR error code 7 reason is fields invalid aka too long or too short. i.e. password not match, user, other fields.

  /products:
    get:
      tags:
        - Products
      summary: Lists products with pagination, doubles as the product search endpoint
      description: >-
        permission manager returns all orders by default, permission client returns only orders from the client itself. Clients will omit disabled/out of stock products by default. Further filtering should be done at client side, or notify devs in order to consider adding a dashboard endpoint with custom filtering for this table. i.e. filter by only disabled, only out of stock, only updated by, created at dates. more precise queries.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            minimum: 1
            default: 10
        - in: query
          name: category
          schema:
            type: array
            items:
              type: integer
          description: A comma separated list of category ids
        - in: query
          name: search
          schema:
            type: string
          description: a text parameter to search for in name and description.
        - in: query
          name: likes
          schema:
            type: boolean
            default: false
          description: returns only products the user has liked, ignores if anonymous
        - in: query
          name: include_images
          schema:
            type: boolean
            default: true
          description: includes the URLs of the images, if false omits this. Useful for administrative dashboards which dont use an image or for other text only UIs.
        - in: query
          name: sort_by
          schema:
            type: string
          description: accepts a field name to order the items by. ASC by default, if - on start of string is DESC.
          examples:
            by_price:
              summary: High to Low price
              value: '-price '
            by_name:
              summary: A to Z name
              value: 'name'

      responses:
        '200':
          description: an array of products filtered according to the specified parameters. also includes pagination details
          content:
            application/json:
              examples:
                search result:
                  value: |-
                    {
                        "products":[{},{}],
                        "count":2,
                        "total_count": 982,
                        "current_page":99,
                        "total_pages":99,
                        "next?": false,
                        "previous?": true
                    }
        '404':
          description: no items match query
        '400':
          description: error invalid query inputs (comma separated list or an array of strings with name of fields which failed validation)
        '429':
          description: error with rate limit, this endpoint is available to anonymous users so a rate limit is needed.
    post:
      tags:
        - Products
      summary: creates a new product
      description: Requires Write Permission (Manager Create Permit).
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Apple iPhone SE 2025
              details: The all new BUDGET iphone SE with AI ......
              price: 999.99
              stock: 3000
              images: [1,2,3,4,6]
      responses:
        '200':
          description: ' product created sucesfuly, returns the product object, the api updates the timestamps and tracks the id of the user to the created by'
        '400':
          description: one or more fields are invalid. returns list of fields and errors.
        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'
  /products/{id}:
    get:
      tags:
        - Products
      summary: gets a specific product by id
      description: >-
        some of the details like if the product has been like are included in the case of a client.
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: a product object with the extra field of liked if user is logged in and of type client.
          content:
            application/json:
              examples:
                search result:
                  value: |-
                    {
                        ...data,
                        liked: boolean
                    }
        '404':
          description: no items with that id
        '400':
          description: error invalid input (sent a string for example)
        '429':
          description: error with rate limit, this endpoint is available to anonymous users so a rate limit is needed.
    put:
      tags:
        - Products
      summary: updates a product data
      description: Requires Write Permission (Manager Update Permit). Only id and one field is required. This endpoint is for requirements of updating a product and disable toggle.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Apple iPhone SE 2025
              details: The all new BUDGET iphone SE with AI ......
              price: 999.99
              stock: 3000
              images: [1,2,3,4,6]
              disabled: false
      responses:
        '200':
          description: ' product created sucesfuly updated, returns the updated object, the api updates the timestamps and tracks the id of the user to the updated by, any omitted field is not updated.'
        '400':
          description: one or more fields are invalid. returns list of fields and errors.
        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'
        '404':
          description: product with id X not found
    delete:
      tags:
        - Products
      summary: deletes a specified product
      description: >-
        because cascading to delete a product will probably also delete it from orders, this only updates field deleted to true, this will make sure it is omitted from queries except such as old orders. This also serves as an identifier so that once orders are closed a cleanup task can be performed.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'delete successful OR product already deleted'
        '404':
          description: product id not found
        '400':
          description: invalid id value
        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'

  /orders:
    get:
      tags:
        - Orders
      summary: Lists orders with pagination, doubles as the order search endpoint (search mostly for managers)
      description: >-
        depending on permissions will return limited fields and will omit disabled/out of stock products. Further filtering should be done at client side, or notify devs in order to consider adding a dashboard endpoint with custom filtering for this table. i.e. filter by only disabled, only out of stock, only updated by, created at dates. more precise queries.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            minimum: 1
            default: 10
        - in: query
          name: order_status
          schema:
            type: integer
          description: A status id to filter the results by
        - in: query
          name: payment_status
          schema:
            type: integer
          description: A status id to filter the results by
        - in: query
          name: search
          schema:
            type: string
          description: a text parameter to search for in client names and email or order number
        - in: query
          name: sort_by
          schema:
            type: string
          description: accepts a field name to order the orders by. ASC by default, if - on start of string is DESC.
          examples:
            by_price:
              summary: Oldest to Recent
              value: '-created_at '
            by_name:
              summary: Delivery Status
              value: 'order_status'
      responses:
        '200':
          description: an array of orders filtered according to the specified parameters. also includes pagination details
          content:
            application/json:
              examples:
                search result:
                  value: |-
                    {
                        "orders":[{},{}],
                        "count":2,
                        "total_count": 982,
                        "current_page":99,
                        "total_pages":99,
                        "next?": false,
                        "previous?": true
                    }
        '404':
          description: no items match query OR user doesnt have orders (when role is client and this wants to return only his orders. or should it return empty array?)
        '400':
          description: error invalid query inputs (comma separated list or an array of strings with name of fields which failed validation)

        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'
    post:
        tags:
          - Orders
        summary: creates a new order
        description: Requires an account, an array of items in cart that are to be purchased.
        requestBody:
          required: true
          content:
            application/json:
              example:
                cart_item_ids: [1,2,3,4,56]
                other_info: like_address
        responses:
          '200':
            description: >-
                order placed, the api will automatically assign the client id to the user id of the submitting user. this call will also copy the items from the cart into the order details and remove them from cart. The timestamp, and statuses will be set by default. An order is created before the first payment attempt is made. Thus the app has to hit the payments endpiont once there is an intent.
            content:
              application/json:
                example:
                  order_id: 1234
          '400':
            description: 'invalid data. The list is in a wrong format or has items which are not in the customer cart.'
          '401':
            description: 'user not logged in'
          '403':
            description: 'user role doenst have the necessary permit'
  /orders/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      tags:
        - Orders
      responses:
        '200':
          description: ok, returns order object and the list of the object details.
          content:
            application/json:
              examples:
                search result:
                  value: |-
                    {
                        "order": {},
                        "items": [{},{}]
                    }
        '400':
          description: id is invalid format
        '404':
          description: order with that id not found
        '401':
          description: 'user not logged in'
        '403':
          description: 'order queried is not from the user. blocked'


  /files:
    post:
      tags:
        - System
      summary: creates a new file
      description: Requires Write Permission (Manager Upload Permit). This endpoint receives a base64 encoded file, then it uploads it to a CDN, when it gets a response with a url it then creates a file entry with the file metadata like the size and a timestamp.
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: photo.png
              base64: 'aaaaaaaaaaaaadddddddddddddddddd3333333333344444'
      responses:
        '200':
          description: 'file upload in progess'
        '400':
          description: one or more fields are invalid. returns list of fields and errors.
        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'
  /carts:
    post:
      tags:
        - Carts
      summary: creates a new entry of an item in the cart
      description: adds a product id + user id entry row to the cart table. Specifies the quantity in the cart.
      requestBody:
        required: true
        content:
          application/json:
            example:
              product_id: 3
              quantity: 1
      responses:
        '200':
          description: ' product created sucesfuly, returns the cart object, the api adds the timestamps and the user that submitted the request'
        '400':
          description: one or more fields are invalid. returns list of fields and errors.
        '401':
          description: 'user not logged in'
        '403':
          description: 'user role doenst have the necessary permit'
  /likes:
    post:
      tags:
        - Likes
      summary: a user submits a product to like.
      description: This wont fail if the user tries to send a like for an already liked product. The api automatically adds the user id as the one sending the request.
      requestBody:
        required: true
        content:
          application/json:
            example:
              product_id: 5
      responses:
        '200':
          description: 'successfully added to likes/already in likes'
        '400':
          description: the id is not valid.
        '401':
          description: 'user not logged in'
        '429':
          description: error with rate limit, since we dont fail in case the api is hit many times just rate limit it.
