openapi: 3.0.3
info:
  title: Ezra e-commerce
  version: '-1.seven.3'
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Validates credentials with server and returns the user object.
      description: >-
        Login or login attempt email is sent. Checks for login attempts and locks account if too many attempts were made.
      requestBody:
        description: user email, password
        required: true
        content:
          application/json:
            example:
              email: me@email.com
              password: supersafe123!
      responses:
        '200':
          description: >-
            credentials are valid, responds with user object. resets failed login attempts. Updates last login at. and clears the password reset timestamps.
        '400':
          description: >-
            error reason is too many failed attempts, the account is locked, please reach out to support. (this is ridiculous but banks do this kind of stuff)
        '401':
          description: >-
            credentials are invalid, error code 3 reason wrong password. Increases the attempts count and adds a timestamp to the attempts timestamp log.
        '404':
          description: >-
            credentials are invalid, error code 4 reason account does not exists.
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logs the user out.
      description: >-
        This updates the last loged at timestamp. This is a post because we want
        to fail on further calls with already loged out or other errors.
      responses:
        '200':
          description: logged out succesfully!
        '400':
          description: user has already logged out / session has expired. these edge cases wont update last logout timestamp.
          content:
            application/json:
              examples:
                already logged out:
                  value: |-
                    {
                        "code":1,
                        "reason":"user has already logged out"
                    }
                user tried to logout but session was expired:
                  value: |-
                    {
                        "code": 2,
                        "reason": "user attempted to log out after the session expired (last login was over 72 hours ago)"
                    }

